name: sf_env
channels:
  - snowflake
dependencies:
  # Core packages available in Snowflake
  - streamlit
  - pandas
  - numpy
  - plotly
  - altair
  - matplotlib
  - seaborn
  - scipy
  - pyarrow
  - xlsxwriter
  - python-dotenv
  
  # Snowflake packages (typically pre-installed)
  - snowflake-snowpark-python
  
  # Note: snowflake-connector-python is typically pre-installed in Snowflake Streamlit
  # Only add additional packages that are confirmed to be available in Snowflake's Anaconda channel 